# Generated by Django 4.1.5 on 2023-02-11 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_alter_category_table_subcategory'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subcategory',
            table='subcategory',
        ),
    ]
