# Generated by Django 4.1.5 on 2023-02-16 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_inquiry',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
