# Generated by Django 4.1.5 on 2023-02-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customer_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_feedback',
            name='rating',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
