# Generated by Django 4.1.5 on 2023-02-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_customer_feedback_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('phone_no', models.BigIntegerField()),
                ('email', models.CharField(max_length=50)),
                ('password', models.BigIntegerField()),
            ],
            options={
                'db_table': 'cust_register',
            },
        ),
    ]
