# Generated by Django 4.1.5 on 2023-03-16 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_alter_subcategory_table'),
        ('user', '0006_customer_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('price', models.BigIntegerField()),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=250)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.subcategory')),
            ],
            options={
                'db_table': 'upload_product',
            },
        ),
        migrations.DeleteModel(
            name='Customer_register',
        ),
    ]
