# Generated by Django 4.1.5 on 2023-03-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_upload_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_product',
            name='largedes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='upload_product',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
