# Generated by Django 4.1.5 on 2023-03-18 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_upload_product_largedes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_product',
            name='date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
