# Generated by Django 4.1.5 on 2023-03-18 14:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0010_upload_product_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('price', models.BigIntegerField()),
                ('description', models.CharField(max_length=200, null=True)),
                ('largedes', models.TextField(null=True)),
                ('image', models.CharField(max_length=250)),
                ('cart_date', models.DateField(default=datetime.date.today, null=True)),
                ('uploader', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
