# Generated by Django 4.1.5 on 2023-03-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_cart_store_user_alter_cart_store_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_product',
            name='contact',
            field=models.BigIntegerField(null=True),
        ),
    ]
