# Generated by Django 4.1.5 on 2023-03-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_upload_product_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_store',
            name='sellercontact',
            field=models.BigIntegerField(null=True),
        ),
    ]
