# Generated by Django 4.1.5 on 2023-03-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_cart_store_sellercontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
