# Generated by Django 4.1.5 on 2023-03-30 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_password_all'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload_product',
            name='subcategory',
        ),
    ]
