# Generated by Django 4.1.5 on 2023-03-30 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_alter_subcategory_table'),
        ('user', '0017_remove_upload_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_product',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.subcategory'),
        ),
    ]
